// Generated by scripts/find-case-studies.ts. Don't edit by hand.
import type { Walkthrough } from "../walkthroughs/types";
import cs0 from "./data/real-candle-2.json";
import cs1 from "./data/real-candle-3.json";
import cs2 from "./data/real-cisd.json";
import cs3 from "./data/real-fvg.json";
import cs4 from "./data/real-order-block.json";
import cs5 from "./data/real-liquidity.json";
import cs6 from "./data/real-bos-choch.json";
import cs7 from "./data/real-nwog.json";
import cs8 from "./data/real-judas.json";
import cs9 from "./data/real-silver-bullet.json";
import cs10 from "./data/real-pdh-pdl.json";
import cs11 from "./data/real-power-of-three.json";
import cs12 from "./data/real-expansion-week.json";
import cs13 from "./data/real-candle-count.json";
import cs14 from "./data/real-smt.json";
import cs15 from "./data/real-ote.json";

const ALL = [cs0, cs1, cs2, cs3, cs4, cs5, cs6, cs7, cs8, cs9, cs10, cs11, cs12, cs13, cs14, cs15] as unknown as Walkthrough[];

export const CASE_STUDIES: Record<string, Walkthrough> = Object.fromEntries(ALL.map((w) => [w.id, w]));

export function getCaseStudy(id: string): Walkthrough | null {
  return CASE_STUDIES[id] ?? null;
}
